// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edisqdyywdfcwxrnewqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkaXNxZHl5d2RmY3d4cm5ld3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MTM0ODAsImV4cCI6MjA3Mzk4OTQ4MH0.avfOrK0TNXc4J_U91G6BRDWgi2_jqd5e--eBSORN_EE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});